[project]
name = "roo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.10.1",
    "pyinstaller>=6.14.1",
    "rich>=14.0.0",
    "ruamel-yaml>=0.18.14",
]
