name: 'Docker Cache Setup'
description: 'Setup Docker BuildKit cache for self-hosted or GitHub runners'
inputs:
  cache-key:
    description: 'Cache key for Docker build cache'
    required: true
  cache-type:
    description: 'Type of cache (buildkit or registry)'
    required: false
    default: 'buildkit'
outputs:
  cache-from:
    description: 'Cache sources for Docker build'
    value: ${{ steps.setup-cache.outputs.cache-from }}
  cache-to:
    description: 'Cache destinations for Docker build'
    value: ${{ steps.setup-cache.outputs.cache-to }}
  runner-type:
    description: 'Detected runner type (self-hosted or github)'
    value: ${{ steps.setup-cache.outputs.runner-type }}
runs:
  using: 'composite'
  steps:
    - name: Setup Docker cache
      id: setup-cache
      shell: bash
      run: |
        # æ£€æµ‹runnerç±»åž‹
        if [[ "${{ runner.name }}" == *"lazy"* ]] || [[ "${{ runner.os }}" == "Linux" && -d "/tmp/action" ]]; then
          runner_type="self-hosted"
          echo "ðŸ  æ£€æµ‹åˆ°è‡ªå»ºrunner: ${{ runner.name }}"
        else
          runner_type="github"
          echo "â˜ï¸ æ£€æµ‹åˆ°GitHubæ‰˜ç®¡runner: ${{ runner.name }}"
        fi

        echo "runner-type=$runner_type" >> $GITHUB_OUTPUT

        # æ ¹æ®runnerç±»åž‹é…ç½®ç¼“å­˜
        if [[ "$runner_type" == "self-hosted" ]]; then
          # è‡ªå»ºrunnerä½¿ç”¨æœ¬åœ°ç¼“å­˜
          cache_dir="/tmp/action/docker-cache"
          mkdir -p "$cache_dir"

          cache_from="type=local,src=$cache_dir"
          cache_to="type=local,dest=$cache_dir,mode=max"

          echo "ðŸ“ ä½¿ç”¨æœ¬åœ°Dockerç¼“å­˜: $cache_dir"
        else
          # GitHub runnerä½¿ç”¨GitHub Actions cache
          cache_from="type=gha"
          cache_to="type=gha,mode=max"

          echo "â˜ï¸ ä½¿ç”¨GitHub Actionsç¼“å­˜"
        fi

        echo "cache-from=$cache_from" >> $GITHUB_OUTPUT
        echo "cache-to=$cache_to" >> $GITHUB_OUTPUT