apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: lazyai-studio

namespace: lazyai-studio

resources:
  - namespace.yaml
  - configmap.yaml
  - persistent-volumes.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: lazyai-studio
  managed-by: kustomize

images:
  - name: lazygophers/lazyai-studio
    newTag: latest

replicas:
  - name: lazyai-studio
    count: 1