[project]
name = "lazygopher"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "appdirs>=1.4.4",
    "black>=25.1.0",
    "mcp>=1.10.1",
    "psutil>=7.0.0",
    "pyinstaller>=6.14.1",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]
