[project]
name = "lazygopher"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "shutup>=0.2.0",
]
